version: "3"
services:
  database:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    container_name: MySQLdatabase
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
    networks:
      testing_net:
        ipv4_address: 172.26.1.2
  app1:
    build: ./app
    links:
    - database
    container_name: app1
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
    networks:
      testing_net:
        ipv4_address: 172.26.1.3
  app2:
    build: ./app
    links:
    - database
    container_name: app2
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
    networks: 
      testing_net:
        ipv4_address: 172.26.1.4
  proxy1:
    build:
      context: ./proxy
      dockerfile: Dockerfile1
    container_name: proxy1
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
    links:
      - app1
    networks: 
        testing_net:
          ipv4_address: 172.26.1.6
  proxy2:
    build:
      context: ./proxy
      dockerfile: Dockerfile2
    container_name: proxy2
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
    links:
      - app2
    networks: 
        testing_net:
          ipv4_address: 172.26.1.7
  nginx:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: nginx
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
    ports:
      - "80:80"
    links:
      - proxy1
      - proxy2
    networks: 
        testing_net:
          ipv4_address: 172.26.1.8
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/16
